### ISSUE TITLE
youdao api text truncate problem

### ISSUE THREAD

**Issue by gzskyking** [shinalone/translators#2]
`text = "PC Players: The recent lobby connectivity issues have now been resolved. https://twitter.com/PUBG_Support/status/1106138075493744642 …"`

> form
{'i': 'PC Players: The recent lobby connectivity issues have now been resolved. https://twitter.com/PUBG_Support/status/1106138075493744642\xa0…', 'from': 'AUTO', 'to': 'AUTO', 'smartresult': 'dict', 'client': 'fanyideskweb', 'ts': '1553074717864', 'salt': '15530747178642', 'sign': '6670e79e923ee7c2d1e1f81a09fe76b0', 'bv': '43e486d853ef63af6932375b449635ab', 'doctype': 'json', 'version': '2.1', 'keyfrom': 'fanyi.web', 'action': 'FY_BY_REALTIME', 'typoResult': 'false'}

> result
`{'translateResult': [[{'tgt': 'PC玩家:最近大厅连接问题', 'src': 'PC Players: The recent lobby connectivity issues h'}]], 'errorCode': 0, 'type': 'en2zh-CHS'}`

**Comment by shinalone** [comment]
It is recommended that you use `'''your text'''`.

**Comment by gzskyking** [comment]
It works. Thanks
